apiVersion: v1
kind: Service
metadata:
  name: rtfc-app-service
  labels:
    app.kubernetes.io/instance: rtfc-release-hazelcast
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: rtfc-release-hazelcast
    role: hazelcast
  ports:
  - name: hazelcast-wan
    protocol: TCP
    port: 5710    # Service port
    targetPort: 5710 # Container port
