apiVersion: v1
kind: Service
metadata:
  name: mancenter-service
  labels:
    app.kubernetes.io/instance: mancenter-my-release
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: mancenter-my-release
    role: mancenter
  ports:
  - name: hazelcast-mc
    protocol: TCP
    port: 8443    # Service port
    targetPort: 8443 # Container port
