apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app.kubernetes.io/instance: my-release-hazelcast
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: my-release-hazelcast
    role: hazelcast
  ports:
  - name: hazelcast-wan
    protocol: TCP
    port: 5710    # Service port
    targetPort: 5710 # Container port
  - name: hazelcast-client
    protocol: TCP
    port: 5701    # Service port
    targetPort: 5701 # Container port