apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pdcs-app
  labels:
    app: pdcs-app
    app.kubernetes.io/instance: pdcs-release-hazelcast
    role: hazelcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdcs-app
      app.kubernetes.io/instance: pdcs-release-hazelcast
      role: hazelcast
  template:
    metadata:
      labels:
        app: pdcs-app
        app.kubernetes.io/instance: pdcs-release-hazelcast
        role: hazelcast
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              "app.kubernetes.io/instance": pdcs-release-hazelcast
      terminationGracePeriodSeconds: 600
      serviceAccountName: pdcs-sa
      containers:
        - name: pdcs-app-container
          image: wsonelab/hazelcast-embedded-kubernetes:latest  #<to-update>
          imagePullPolicy: Always
          resources: 
            requests:
              memory: 256Mi  #<to-update>
              cpu: 100m  #<to-update>
            limits:
              memory: 1024Mi  #<to-update>
              cpu: 200m  #<to-update>
          livenessProbe:
            httpGet:
              path:  /hazelcast/health/node-state
              port: 5703
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /hazelcast/health/ready
              port: 5703
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: hz-config-volume
              mountPath: /app/hazelcast.yaml
              subPath: hazelcast.yaml
            - name: hz-persistence-volume
              mountPath: /data/persistence
            - name: hz-certificates-volume
              mountPath: /data/secrets
          env:
            - name: JMX_OPTS
              #<to-update> sample from  -Xms512Mi -Xmx512Mi  to actual value
              value: "-Xms512Mi -Xmx512Mi -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/hazelcast/jvm -XX:ErrorFile=/var/log/hazelcast/jvm/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/hazelcast/jvm/gc.log:utctime,pid,tags:filecount=32,filesize=64m"
            - name: JAVA_OPTIONS
              value: "$(JMX_OPTS) -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true  -Dhazelcast.graceful.shutdown.max.wait=600 -Dhazelcast.cluster.version.auto.upgrade.enabled=true -Dhazelcast.stale.join.prevention.duration.seconds=5 -Dhazelcast.config=/app/hazelcast.yaml "
            - name: HZ_LICENSEKEY
              valueFrom:
                secretKeyRef:
                  name: hz-license-key
                  key: key
      volumes:
        - name: hz-config-volume
          configMap:
            name: hz-config
        - name: hz-certificates-volume
          secret:
            secretName: hz-certificates  # References the secret
  volumeClaimTemplates:
    - metadata:
        name: hz-persistence-volume
        labels:
          app.kubernetes.io/instance: pdcs-release-hazelcast
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ""   #<to-update>
        resources:
          requests:
            storage: 1Gi #<to-update>
          
   
  